package com.dennis.entity.enums;

public enum EDepartmant {
    DEPARTMENT_OF_CARDIOLOGY,
    DEPARTMENT_OF_ORTHOPEDICS,
    DEPARTMENT_OF_EAR_NOSE_THROAT,
    DEPARTMENT_OF_PSYCHİATRY,
    DEPARTMENT_OF_BRAIN_SURGERY,
    DEPARTMENT_OF_INTERNAL_MEDICINE,
}
